apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pods-nginx
  name: pods-nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources: 
      limits:
        cpu: "0.5"
        memory: "256Mi"
      requests:
        cpu: "0.3"
        memory: "128Mi"      
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
        
